# Generated by Django 4.2 on 2024-06-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_inmueble_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre y apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('contact_type', models.IntegerField(choices=[[0, 'Pedido de información'], [1, 'Queja de un producto'], [2, 'Felicitaciones']], verbose_name='Tipo de contacto')),
                ('suscription', models.BooleanField(default=False, verbose_name='Suscribirme a correos informativos')),
                ('create_ad', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envio')),
            ],
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
    ]
